### PR TITLE
New AOL script (incl. lang & icon fixes) and related Handler script update (const ST_LOGOUT)

### PR DESCRIPTION
**Pull request by jeroen1956**

### CODE REVIEW

**Comment by Loirooriol** [comment]
I'm afraid it's a bit too late, non-bootstrapped legacy extensions no longer work on Firefox 61, which will become beta very soon. Or are you using some Firefox fork?

**Comment by jeroen1956** [comment]
Yes, ewwink's X-notifier Reloaded forkoff from X-notifier 3.5.23 serving
Firefox pre 57 (56.0.2)

https://github.com/ewwink/X-Notifier-Reloaded  now on (3.5.26)

But that is no news to you, is it?

http://xnotifier.tobwithu.com/dp/forum/1

2018-04-21 20:26 GMT+02:00 Oriol Brufau <notifications@github.com>:

**Comment by Loirooriol** [comment]
Ah, you just stayed in an old version. I also disabled Nightly updates for the moment, but that's so bad. I am developing a webext-based mail notifier (tobwithu's one just doesn't work), but it's very difficult.

**Comment by jeroen1956** [comment]
I think you mean the one you forked off from tobwithu's version 3 called
Z-notifier?
I have it (3.1) installed on (Portable) Firefox Developer Edition 60.0b14.
It's not working for me. Only for POP3 (Tele2 Versatel) and Facebook
(adapted by me), Not working: Gmail, Hotmail, Yahoo, LinkedIn, GMX,
OpenMailbox, Zoho.

X-notifier Reloaded works for me on Firefox 56.0.2 for Gmail, POP3,
Facebook, Hotmail, Yahoo, LinkedIn, GMX, OpenMailbox, Zoho and AOL (but all
but Gmail got updated by me).
X-notifier 4.2.1 works for me on (Portable) Firefox Test Edition 60.0b14
and on (Portable) Firefox Nightly 61.0a1 for Gmail, Hotmail, Yahoo,and AOL

2018-04-21 21:04 GMT+02:00 Oriol Brufau <notifications@github.com>:

**Comment by Loirooriol** [comment]
@jeroen1956 That fork is still non-bootstrapped legacy, and it stopped working in 61. I only use Hotmail and IMAP and they work for me in Developer Edition 60.0b14 and old Nightly 61. I haven't tested the portable ones, though. But in the previous comment I meant that I am now trying to rewrite this from scratch into a webextension, but it's a long-term project.

**Comment by jeroen1956** [comment]
Ah, good luck with that...
I use portable to enable running the various Firefox editions parallel.
Portable should make no difference in behavior: same application, just
different folder config.

2018-04-22 0:00 GMT+02:00 Oriol Brufau <notifications@github.com>:

**Pull request merged**
